version: '3.8'

services:
  sep4-java-env:
    build:
      context: ../backend/iot-backend
      dockerfile: Dockerfile
    image: sep4-java-env
    container_name: iot-container
    ports:
      - "5040:8080"  # Access service at localhost 5040
    working_dir: /app
    volumes:
      - ../backend/iot-backend:/app
    stdin_open: true
    tty: true