services:
  sep4-python-env:
    build:
      context: ..
      dockerfile: Dockerfile
    image: sep4-java-env
    container_name: iot-container
    volumes:
      - ../:/tmp
    working_dir: /tmp
    command: bash
    stdin_open: true
    tty: true
